name: Continuous integration
on: [push, pull_request]

jobs:
    build-unixes:
        name: Build Linux
        runs-on: ${{ matrix.variant.os }}
        strategy:
            matrix:
                variant:
                    - os: ubuntu-latest
                      platformName: linux64
                      buildMode: RelWithDebInfo
        env:
            PLATFORM_NAME: ${{ matrix.variant.platformName }}
            BUILD_MODE: ${{ matrix.variant.buildMode }}
            PROJECT_NAME: sysmel
        steps:
            - name: Install dependencies linux
              run: sudo apt-get update && sudo apt-get -qqy install gcc-multilib libsdl2-dev libsdl2-dev:i386

            - uses: actions/checkout@v1

            - name: CI Build
              run: ./scripts/build/buildAll.sh

            - name: CI Tests
              run: ./build-bootstrap/linux/x64/phase2 -p "TestCase runWithAllSubclasses"
